### ISSUE TITLE
Is this gem still maintained?

### ISSUE THREAD

**Issue by zedtux** [why-el/dragula-rails#2]
The gem has a single version, which is an old version, and a PR is opened since months. I can maintain it if you give the write rights on rubygems.org.

**Comment by zedtux** [comment]
I just built a Github repo with an up-to-date and automatised build using Docker at https://github.com/Sento/dragula-rails.

If you give me write access to rubygems.org, I could push an up-to-date version of the library and I'll maintain it.

**Comment by zedtux** [comment]
@why-el also you did only one commit since 2015, let's refresh it and give me write access on rubygems.org :)

**Comment by why-el** [comment]
Hey @zedtux I actually did not receive any emails until you tagged me, and the same goes for the open PR. It's a little weird why that happens. I will merge that PR and push the new version.

**Comment by zedtux** [comment]
Thank you @why-el for this.

Nonetheless it looks like you're not following dragula, meaning releasing new version of this gem when new versions of dragula are released.
I am maintaining a dozen of gems similar as this one, in an automated way.

If you give me the write access to rubygems.org, I will be able to push updates quickly (like now, you're still late, even with the PR you've merged).

**Comment by why-el** [comment]
Wouldn't it make sense to add you as a contributor here in GitHub as well?

**Comment by zedtux** [comment]
I did another repo as a lot of files was to be changed (I used `bundler gem` in order to build the gem) also because I wasn't sure to get a reply from you.

I can do a merge request, but the 2 repos are different.

**Comment by why-el** [comment]
I think it's easier for me if you make a merge request, instead of having
two repos pushing to ruby gems.

**Comment by zedtux** [comment]
Well then you have to be reactive in order to accept pull request and package/push the gem to rubygems (what my repo is doing automatically).

**Comment by zedtux** [comment]
Damned, as I didn't forked your repo, I can't create a PR.

**Comment by zedtux** [comment]
Maybe you can try to clone and then merge my repo?

**Comment by why-el** [comment]
I am not sure what you mean. But in any case it should be ok for you to create a PR here, and I will merge it if its a newer version.

**Comment by zedtux** [comment]
What I mean is that I didn't forked your repository. Now Github doesn't recognise that my repo could be merged with yours.
I'm trying to create the PR but I can't.

Now the only way is to do it manually. You have to [add a new remote in your repository on your machine](https://help.github.com/articles/configuring-a-remote-for-a-fork/) pointing to my repo, then [fetch it, and then merge my master with your master](http://blogs.atlassian.com/2013/07/git-upstreams-forks/) (like you would do with an upstream remote).

**Comment by why-el** [comment]
I unfortunately don't have time to do what you asked nor do I know why it is not possible for you to create a PR, normally it's trivial. Let me know if you get it working, but the only way to get code to this repository is through PRs, the standard way. Thanks.

**Comment by zedtux** [comment]
Once again, as I said before, as I haven't forked your repo, Github is not offering me the choice to select my repo in order to create the PR. Our repos are un-sync.

Here is what I have:

![screen shot 2016-11-28 at 20 13 15](https://cloud.githubusercontent.com/assets/478564/20682155/1eaddeba-b5a7-11e6-841f-1468a84feea2.png)

As you can see, I can't select my repo.

**Comment by why-el** [comment]
You can't create a PR without forking.

**Comment by zedtux** [comment]
That's what I'm trying to say since few comments :)

**Comment by zedtux** [comment]
Anyway, I found a way to make it working and be able to do what I was asking you. Now you have a PR with some explanation.

Please watch the new releases of Dragula and update this gem regularly :)

Just to link the PR and this issue: #3
